.

diff --git a/.pipelines/azdo-base-pipeline.yml b/.pipelines/azdo-base-pipeline.yml
--- a/.pipelines/azdo-base-pipeline.yml
+++ b/.pipelines/azdo-base-pipeline.yml
@@ -1,26 +1,44 @@
-# this pipeline should be ignored for now
-parameters:
-  pipelineType: 'training'
+jobs:
+- job: Environment
+  displayName: "Set up build environment"
+  steps:
+  - task: AzureCLI@1
+    displayName: Generate build container
+    name: SetContainer
+    inputs:
+      azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+      scriptLocation: inlineScript
+      inlineScript: |
+        set -euxo pipefail  # fail on error
+        imageTag=$(find docker -type f -exec md5sum {} \; | sort -k 2 | md5sum | cut -f1 -d ' ')
+        imageName="$(ACR).azurecr.io/modelbuild/$(BUILDCONTAINER_NAME)"
+        if ! az acr repository show -n $(ACR) --image "modelbuild/$(BUILDCONTAINER_NAME):$imageTag" -o table; then
+          az acr build \
+            -r $(ACR) \
+            -t "$imageName:$imageTag" \
+            -t "$imageName:latest" \
+            docker
+        fi
+        echo "##vso[task.setvariable variable=BUILD_IMAGE;isOutput=true]$imageName:$imageTag"
+      workingDirectory: azureml
 
-steps:
-- script: |
-   flake8 --output-file=$(Build.BinariesDirectory)/lint-testresults.xml --format junit-xml  
-  workingDirectory: '$(Build.SourcesDirectory)'
-  displayName: 'Run code quality tests'
-  enabled: 'true'
-  
-- script: |
-   pytest --junitxml=$(Build.BinariesDirectory)/unit-testresults.xml $(Build.SourcesDirectory)/tests/unit
-  displayName: 'Run unit tests'
-  enabled: 'true'
-  env:
-    SP_APP_SECRET: '$(SP_APP_SECRET)'
+- job: "Model_CI_Pipeline"
+  displayName: "Model CI Pipeline"
+  dependsOn: Environment
+  variables:
+    BUILD_IMAGE: $[ dependencies.Environment.outputs['SetContainer.BUILD_IMAGE'] ]
+  container:
+    image: $(BUILD_IMAGE)
+    endpoint: aml-acr-connection
+  timeoutInMinutes: 0
+  steps:
 
-- task: PublishTestResults@2
-  condition: succeededOrFailed()
-  inputs:
-    testResultsFiles: '$(Build.BinariesDirectory)/*-testresults.xml'
-    testRunTitle: 'Linting & Unit tests'
-    failTaskOnFailedTests: true
-  displayName: 'Publish linting and unit test results'
-  enabled: 'true'
+  - script: |
+     flake8 --output-file=$(Build.BinariesDirectory)/lint-testresults.xml --format junit-xml
+    workingDirectory: '$(Build.SourcesDirectory)'
+    displayName: 'Run code quality tests'
+
+  - script: |
+     pytest test/unit --cov=code --cov-report=html --junitxml=$(Build.BinariesDirectory)/unit-testresults.xml  --nunitxml="*-testresults.xml"
+    workingDirectory: azureml
+    displayName: 'Run unit tests'
